// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(braird_coreFFI)
import braird_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_braird_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_braird_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * The on-device sync engine. Owns the SQLite [`Store`], the [`PostgrestClient`], the crypto
 * [`Vault`] (for seal-at-write), and a tokio current-thread runtime. `Arc<SyncEngine>` is the
 * UniFFI handle; the interior `Mutex`es make it `Send + Sync` for Swift/Kotlin callers on any
 * thread (same shape as `Vault`).
 */
public protocol SyncEngineProtocol : AnyObject {
    
    /**
     * Enqueue a book upsert. `updated_at` is stamped in epoch ms at enqueue (never omitted —
     * the migration default is 0). Plaintext metadata only, no encryption branch (like the PWA
     * `upsertBook`).
     */
    func enqueueBook(id: String, title: String, author: String?, createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Enqueue a collection upsert (SUR-726). Plaintext metadata only.
     */
    func enqueueCollection(id: String, name: String, createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Enqueue a collection-membership upsert (SUR-726) — a note↔collection pair. The pk is DERIVED
     * here via [`membership_id`] (collection first), never taken from the host, so two devices
     * adding the same pair converge to ONE row (SUR-737 OR-set add). A remove is the same call with
     * `deleted: true`. `created_at` is always carried (the server column is NOT NULL, no default).
     */
    func enqueueCollectionMembership(noteId: String, collectionId: String, createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Enqueue a custom-idea upsert (SUR-726). Plaintext metadata only (mirrors `upsertIdea`);
     * `description` defaults to `""` when absent (the PWA's `|| ''`). `updated_at` stamped at enqueue.
     */
    func enqueueCustomIdea(id: String, name: String, description: String?, createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Enqueue a lens upsert (SUR-726) — ONE authored query. Plaintext; `leaf_ids` is a cloud
     * `text[]` (JSON array on the wire), whole-row LWW (SUR-737 — no leaf union). `combinator` /
     * `threshold` default to `"AND"` / `100` (mirrors `upsertLens`'s `|| 'AND'` / `?? 100`). No
     * client-side range check on threshold — the server CHECK (0..=100) enforces it, like the PWA.
     */
    func enqueueLens(id: String, name: String, leafIds: [String], combinator: String?, threshold: Int64?, createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Enqueue a note upsert — the seal-at-write path. `text` is the PLAINTEXT; it is sealed here
     * (enc:v2, AAD = note id) and `content_tag` is computed here FROM the plaintext (both while
     * the plaintext is in hand). The stored outbox payload holds only the ciphertext + the tag.
     *
     * STALE-TAG EDGE (deliberate, mirrors surfc — do not "fix"): the content_tag bakes in the
     * note's `book_id`, but the flush repoints `book_id` via `bookIdRemap` after an offline
     * book-merge. So a merged note's tag reflects the PRE-merge book_id. The JS never recomputes
     * the tag at flush (`flushOutbox` doesn't touch it), and we CAN'T recompute at flush anyway —
     * under seal-at-write there is no plaintext left. We leave the tag as-is: the rare
     * stale-tag-after-offline-merge self-heals on the note's next edit (which re-enqueues with a
     * freshly-computed tag). The tag is never NULL because it is computed pre-seal, from plaintext.
     */
    func enqueueNote(id: String, bookId: String?, plaintext: String, page: String?, tags: [String], createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Enqueue a note-link upsert (SUR-726) — a parent→child annotation edge. Plaintext only;
     * `relation_type` defaults to `"handwritten_annotation"` (mirrors the surfc column default). A
     * remove is the same call with `deleted: true` (tombstone). Row-per-edge on a random pk (a
     * "bag" in the SUR-737 convergence contract): concurrent adds of the same logical edge do NOT
     * dedup — unlike memberships' deterministic pk.
     */
    func enqueueNoteLink(id: String, fromNoteId: String, toNoteId: String, relationType: String?, createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Enqueue a note-signals upsert (SUR-726) — per-note behavioural counters, keyed by `note_id`
     * (there is NO separate `id` column; the payload carries `note_id` only, matching
     * `upsertNoteSignals`). Whole-row LWW; concurrent increments are lossy but self-heal (SUR-737,
     * ratified — derived data). Params follow the descriptor column order.
     *
     * CONTRACT (mirror of surfc's `ensureNoteSignals`): hosts must NOT enqueue a fresh "birth" row.
     * A birth row is local-only lazy-init; pushing one would clobber another device's earned counters
     * under whole-row LWW. Enqueue only on a genuine behavioural change.
     */
    func enqueueNoteSignals(noteId: String, sourcePrior: Double, returnVisits: Int64, hasAnnotation: Bool, stitchSpawns: Int64, exposureRecencyAt: Int64, engagementRecencyAt: Int64, importance: Double, createdAt: Int64, deleted: Bool) throws 
    
    /**
     * Push every queued write to Supabase (books-first, remap, notes; failed stay queued).
     * Synchronous FFI — the async PostgREST calls run on the owned runtime via `block_on`.
     */
    func flush() throws  -> FlushSummary
    
    /**
     * Pull incrementally from Supabase for **all eight synced tables** (SUR-726 —
     * [`synced_table_names`] is the one source of the pull scope). Merges last-write-wins by
     * `updated_at`, applies tombstones without resurrecting soft-deleted rows, **rebases the outbox**
     * (drops a queued local edit a newer remote row beat — SUR-736 — and reports it in `superseded`,
     * SUR-738), and advances each per-table cursor to the max server `change_seq` it merged
     * (SUR-739 visibility watermark), paging by `change_seq` until a short page (SUR-652). The
     * watermark replaces the old client-clock lookback: a delayed/offline flush is now delivered the
     * moment the server makes it visible, not skipped. Synchronous FFI — the async GETs run on the
     * owned runtime via `block_on`, exactly like `flush`. Note text stays ciphertext at rest (never
     * decrypted on pull); the host decrypts via `Vault::decrypt_note`.
     *
     * Call order is now safe either way for SUR-736: the rebase drops a stale queued edit as it
     * merges the newer remote row, so a following `flush()` can't re-push it. Prefer
     * [`SyncEngine::sync`] (pull-then-flush) for the one-call path. (This does NOT fix SUR-740 — a
     * flush destroying a newer SERVER row before a pull can see it is the server's job, PR-3.)
     */
    func pull() throws  -> PullSummary
    
    /**
     * Hand the core a GoTrue-issued access token (JWT). The core makes its OWN authenticated
     * PostgREST calls with it; the `user_id` stamped on each row is the token's `sub` claim.
     */
    func setAccessToken(jwt: String) 
    
    /**
     * Pull, then flush — the one-call convergence path (SUR-736). Pulls FIRST, then flushes.
     *
     * **Deliberate divergence from the oracle** (surfc's `syncFromCloud` flushes first): with the
     * outbox rebase (SUR-736), pulling first fetches the server's newer row and rebases the stale
     * local edit out of the outbox, so the following flush pushes nothing stale. Flushing FIRST
     * would re-push the stale edit over the newer server row before the pull could see it — the 736
     * lost edit. Same class of documented divergence as the per-table cursor.
     *
     * **The flush is aborted unless the pull was fully clean.** If ANY table's pull failed (partial
     * OR total), `sync()` returns an error and does NOT flush. A failed table never rebased its
     * outbox (its cursor is unadvanced), so flushing it could re-push a stale edit over a newer
     * server row this pull didn't fetch — reopening SUR-736 for that table. This is stricter than
     * calling `pull()` + `flush()` separately (where a partial pull is `Ok` and a subsequent flush
     * runs) — the strictness is the point: `sync()` guarantees rebase-protected convergence or
     * nothing, and the host retries. (This still does NOT fix SUR-740 — a flush destroying a newer
     * SERVER row before this pull could see it is the server's job, PR-3.)
     */
    func sync() throws  -> SyncSummary
    
}

/**
 * The on-device sync engine. Owns the SQLite [`Store`], the [`PostgrestClient`], the crypto
 * [`Vault`] (for seal-at-write), and a tokio current-thread runtime. `Arc<SyncEngine>` is the
 * UniFFI handle; the interior `Mutex`es make it `Send + Sync` for Swift/Kotlin callers on any
 * thread (same shape as `Vault`).
 */
open class SyncEngine:
    SyncEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_braird_core_fn_clone_syncengine(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_braird_core_fn_free_syncengine(pointer, $0) }
    }

    
    /**
     * Open the engine over a store at `db_path`, targeting the Supabase project at
     * `supabase_url` with the public `anon_key`. The [`Vault`] is the caller's unlocked handle
     * (seal-at-write needs the MK). No access token yet — the host hands one over via
     * [`SyncEngine::set_access_token`] once GoTrue has issued it.
     */
public static func `open`(dbPath: String, supabaseUrl: String, anonKey: String, vault: Vault)throws  -> SyncEngine {
    return try  FfiConverterTypeSyncEngine.lift(try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_constructor_syncengine_open(
        FfiConverterString.lower(dbPath),
        FfiConverterString.lower(supabaseUrl),
        FfiConverterString.lower(anonKey),
        FfiConverterTypeVault.lower(vault),$0
    )
})
}
    

    
    /**
     * Enqueue a book upsert. `updated_at` is stamped in epoch ms at enqueue (never omitted —
     * the migration default is 0). Plaintext metadata only, no encryption branch (like the PWA
     * `upsertBook`).
     */
open func enqueueBook(id: String, title: String, author: String?, createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_book(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(title),
        FfiConverterOptionString.lower(author),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Enqueue a collection upsert (SUR-726). Plaintext metadata only.
     */
open func enqueueCollection(id: String, name: String, createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_collection(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Enqueue a collection-membership upsert (SUR-726) — a note↔collection pair. The pk is DERIVED
     * here via [`membership_id`] (collection first), never taken from the host, so two devices
     * adding the same pair converge to ONE row (SUR-737 OR-set add). A remove is the same call with
     * `deleted: true`. `created_at` is always carried (the server column is NOT NULL, no default).
     */
open func enqueueCollectionMembership(noteId: String, collectionId: String, createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_collection_membership(self.uniffiClonePointer(),
        FfiConverterString.lower(noteId),
        FfiConverterString.lower(collectionId),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Enqueue a custom-idea upsert (SUR-726). Plaintext metadata only (mirrors `upsertIdea`);
     * `description` defaults to `""` when absent (the PWA's `|| ''`). `updated_at` stamped at enqueue.
     */
open func enqueueCustomIdea(id: String, name: String, description: String?, createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_custom_idea(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(description),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Enqueue a lens upsert (SUR-726) — ONE authored query. Plaintext; `leaf_ids` is a cloud
     * `text[]` (JSON array on the wire), whole-row LWW (SUR-737 — no leaf union). `combinator` /
     * `threshold` default to `"AND"` / `100` (mirrors `upsertLens`'s `|| 'AND'` / `?? 100`). No
     * client-side range check on threshold — the server CHECK (0..=100) enforces it, like the PWA.
     */
open func enqueueLens(id: String, name: String, leafIds: [String], combinator: String?, threshold: Int64?, createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_lens(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterSequenceString.lower(leafIds),
        FfiConverterOptionString.lower(combinator),
        FfiConverterOptionInt64.lower(threshold),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Enqueue a note upsert — the seal-at-write path. `text` is the PLAINTEXT; it is sealed here
     * (enc:v2, AAD = note id) and `content_tag` is computed here FROM the plaintext (both while
     * the plaintext is in hand). The stored outbox payload holds only the ciphertext + the tag.
     *
     * STALE-TAG EDGE (deliberate, mirrors surfc — do not "fix"): the content_tag bakes in the
     * note's `book_id`, but the flush repoints `book_id` via `bookIdRemap` after an offline
     * book-merge. So a merged note's tag reflects the PRE-merge book_id. The JS never recomputes
     * the tag at flush (`flushOutbox` doesn't touch it), and we CAN'T recompute at flush anyway —
     * under seal-at-write there is no plaintext left. We leave the tag as-is: the rare
     * stale-tag-after-offline-merge self-heals on the note's next edit (which re-enqueues with a
     * freshly-computed tag). The tag is never NULL because it is computed pre-seal, from plaintext.
     */
open func enqueueNote(id: String, bookId: String?, plaintext: String, page: String?, tags: [String], createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_note(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(bookId),
        FfiConverterString.lower(plaintext),
        FfiConverterOptionString.lower(page),
        FfiConverterSequenceString.lower(tags),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Enqueue a note-link upsert (SUR-726) — a parent→child annotation edge. Plaintext only;
     * `relation_type` defaults to `"handwritten_annotation"` (mirrors the surfc column default). A
     * remove is the same call with `deleted: true` (tombstone). Row-per-edge on a random pk (a
     * "bag" in the SUR-737 convergence contract): concurrent adds of the same logical edge do NOT
     * dedup — unlike memberships' deterministic pk.
     */
open func enqueueNoteLink(id: String, fromNoteId: String, toNoteId: String, relationType: String?, createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_note_link(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(fromNoteId),
        FfiConverterString.lower(toNoteId),
        FfiConverterOptionString.lower(relationType),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Enqueue a note-signals upsert (SUR-726) — per-note behavioural counters, keyed by `note_id`
     * (there is NO separate `id` column; the payload carries `note_id` only, matching
     * `upsertNoteSignals`). Whole-row LWW; concurrent increments are lossy but self-heal (SUR-737,
     * ratified — derived data). Params follow the descriptor column order.
     *
     * CONTRACT (mirror of surfc's `ensureNoteSignals`): hosts must NOT enqueue a fresh "birth" row.
     * A birth row is local-only lazy-init; pushing one would clobber another device's earned counters
     * under whole-row LWW. Enqueue only on a genuine behavioural change.
     */
open func enqueueNoteSignals(noteId: String, sourcePrior: Double, returnVisits: Int64, hasAnnotation: Bool, stitchSpawns: Int64, exposureRecencyAt: Int64, engagementRecencyAt: Int64, importance: Double, createdAt: Int64, deleted: Bool)throws  {try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_enqueue_note_signals(self.uniffiClonePointer(),
        FfiConverterString.lower(noteId),
        FfiConverterDouble.lower(sourcePrior),
        FfiConverterInt64.lower(returnVisits),
        FfiConverterBool.lower(hasAnnotation),
        FfiConverterInt64.lower(stitchSpawns),
        FfiConverterInt64.lower(exposureRecencyAt),
        FfiConverterInt64.lower(engagementRecencyAt),
        FfiConverterDouble.lower(importance),
        FfiConverterInt64.lower(createdAt),
        FfiConverterBool.lower(deleted),$0
    )
}
}
    
    /**
     * Push every queued write to Supabase (books-first, remap, notes; failed stay queued).
     * Synchronous FFI — the async PostgREST calls run on the owned runtime via `block_on`.
     */
open func flush()throws  -> FlushSummary {
    return try  FfiConverterTypeFlushSummary.lift(try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_flush(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Pull incrementally from Supabase for **all eight synced tables** (SUR-726 —
     * [`synced_table_names`] is the one source of the pull scope). Merges last-write-wins by
     * `updated_at`, applies tombstones without resurrecting soft-deleted rows, **rebases the outbox**
     * (drops a queued local edit a newer remote row beat — SUR-736 — and reports it in `superseded`,
     * SUR-738), and advances each per-table cursor to the max server `change_seq` it merged
     * (SUR-739 visibility watermark), paging by `change_seq` until a short page (SUR-652). The
     * watermark replaces the old client-clock lookback: a delayed/offline flush is now delivered the
     * moment the server makes it visible, not skipped. Synchronous FFI — the async GETs run on the
     * owned runtime via `block_on`, exactly like `flush`. Note text stays ciphertext at rest (never
     * decrypted on pull); the host decrypts via `Vault::decrypt_note`.
     *
     * Call order is now safe either way for SUR-736: the rebase drops a stale queued edit as it
     * merges the newer remote row, so a following `flush()` can't re-push it. Prefer
     * [`SyncEngine::sync`] (pull-then-flush) for the one-call path. (This does NOT fix SUR-740 — a
     * flush destroying a newer SERVER row before a pull can see it is the server's job, PR-3.)
     */
open func pull()throws  -> PullSummary {
    return try  FfiConverterTypePullSummary.lift(try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_pull(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Hand the core a GoTrue-issued access token (JWT). The core makes its OWN authenticated
     * PostgREST calls with it; the `user_id` stamped on each row is the token's `sub` claim.
     */
open func setAccessToken(jwt: String) {try! rustCall() {
    uniffi_braird_core_fn_method_syncengine_set_access_token(self.uniffiClonePointer(),
        FfiConverterString.lower(jwt),$0
    )
}
}
    
    /**
     * Pull, then flush — the one-call convergence path (SUR-736). Pulls FIRST, then flushes.
     *
     * **Deliberate divergence from the oracle** (surfc's `syncFromCloud` flushes first): with the
     * outbox rebase (SUR-736), pulling first fetches the server's newer row and rebases the stale
     * local edit out of the outbox, so the following flush pushes nothing stale. Flushing FIRST
     * would re-push the stale edit over the newer server row before the pull could see it — the 736
     * lost edit. Same class of documented divergence as the per-table cursor.
     *
     * **The flush is aborted unless the pull was fully clean.** If ANY table's pull failed (partial
     * OR total), `sync()` returns an error and does NOT flush. A failed table never rebased its
     * outbox (its cursor is unadvanced), so flushing it could re-push a stale edit over a newer
     * server row this pull didn't fetch — reopening SUR-736 for that table. This is stricter than
     * calling `pull()` + `flush()` separately (where a partial pull is `Ok` and a subsequent flush
     * runs) — the strictness is the point: `sync()` guarantees rebase-protected convergence or
     * nothing, and the host retries. (This still does NOT fix SUR-740 — a flush destroying a newer
     * SERVER row before this pull could see it is the server's job, PR-3.)
     */
open func sync()throws  -> SyncSummary {
    return try  FfiConverterTypeSyncSummary.lift(try rustCallWithError(FfiConverterTypeSyncError.lift) {
    uniffi_braird_core_fn_method_syncengine_sync(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyncEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SyncEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SyncEngine {
        return SyncEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SyncEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyncEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SyncEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> SyncEngine {
    return try FfiConverterTypeSyncEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncEngine_lower(_ value: SyncEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSyncEngine.lower(value)
}




public protocol VaultProtocol : AnyObject {
    
    /**
     * 64-char lowercase hex content-dedup tag (HMAC-SHA256, 64-byte subkey).
     */
    func contentTag(text: String, bookId: String?)  -> String
    
    /**
     * Decrypt an enc:v1/enc:v2 payload produced by this core OR by the PWA.
     */
    func decryptNote(noteId: String?, ciphertext: String) throws  -> String
    
    /**
     * enc:v2 when `note_id` is `Some` (AAD = UTF-8 noteId); enc:v1 when `None`. Fresh
     * random 12-byte IV per call.
     */
    func encryptNote(noteId: String?, plaintext: String)  -> String
    
    /**
     * Open a blob produced by [`Vault::seal_bytes`].
     */
    func openBytes(sealed: Data, aad: String) throws  -> Data
    
    /**
     * PIN-wrap the owned MK for device transfer (PBKDF2-SHA256 @ 600k → AES-256-GCM).
     */
    func pinWrap(pin: String)  -> WrappedBlob
    
    /**
     * Re-wrap the owned MK for a different credential/device. The Vault already holds
     * the MK, so this is a fresh wrap under `new_prf` (multi-device add).
     */
    func rewrap(newPrf: Data)  -> WrappedBlob
    
    /**
     * Seal arbitrary bytes (e.g. an embedding vector) at rest: `[0x02][IV][ct]`,
     * AAD = noteId. Fresh random IV per call.
     */
    func sealBytes(bytes: Data, aad: String)  -> Data
    
    /**
     * Wrap the owned MK with a PRF-derived key → a storable prf-v1 blob. Salt (32B)
     * and IV (12B) are generated in-core with the CSPRNG — no nonce-reuse footgun.
     */
    func wrapWithPrf(prf: Data)  -> WrappedBlob
    
}

open class Vault:
    VaultProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_braird_core_fn_clone_vault(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_braird_core_fn_free_vault(pointer, $0) }
    }

    
    /**
     * Generate a fresh random 256-bit Master Key in-core. The MK never leaves the
     * handle; persist it with [`Vault::wrap_with_prf`].
     */
public static func generate() -> Vault {
    return try!  FfiConverterTypeVault.lift(try! rustCall() {
    uniffi_braird_core_fn_constructor_vault_generate($0
    )
})
}
    
    /**
     * Redeem a PIN-encrypted device-transfer blob on a new device (PBKDF2 @ 600k).
     */
public static func redeemPinTransfer(transferBlob: WrappedBlob, pin: String)throws  -> Vault {
    return try  FfiConverterTypeVault.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_constructor_vault_redeem_pin_transfer(
        FfiConverterTypeWrappedBlob.lower(transferBlob),
        FfiConverterString.lower(pin),$0
    )
})
}
    
    /**
     * Unlock by decrypting a stored prf-v1 blob with raw PRF bytes (the WebAuthn PRF
     * output, fed to HKDF unchanged). The recovered MK stays inside the handle.
     */
public static func unlock(prf: Data, blob: WrappedBlob)throws  -> Vault {
    return try  FfiConverterTypeVault.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_constructor_vault_unlock(
        FfiConverterData.lower(prf),
        FfiConverterTypeWrappedBlob.lower(blob),$0
    )
})
}
    

    
    /**
     * 64-char lowercase hex content-dedup tag (HMAC-SHA256, 64-byte subkey).
     */
open func contentTag(text: String, bookId: String?) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_content_tag(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterOptionString.lower(bookId),$0
    )
})
}
    
    /**
     * Decrypt an enc:v1/enc:v2 payload produced by this core OR by the PWA.
     */
open func decryptNote(noteId: String?, ciphertext: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_method_vault_decrypt_note(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(noteId),
        FfiConverterString.lower(ciphertext),$0
    )
})
}
    
    /**
     * enc:v2 when `note_id` is `Some` (AAD = UTF-8 noteId); enc:v1 when `None`. Fresh
     * random 12-byte IV per call.
     */
open func encryptNote(noteId: String?, plaintext: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_encrypt_note(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(noteId),
        FfiConverterString.lower(plaintext),$0
    )
})
}
    
    /**
     * Open a blob produced by [`Vault::seal_bytes`].
     */
open func openBytes(sealed: Data, aad: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_method_vault_open_bytes(self.uniffiClonePointer(),
        FfiConverterData.lower(sealed),
        FfiConverterString.lower(aad),$0
    )
})
}
    
    /**
     * PIN-wrap the owned MK for device transfer (PBKDF2-SHA256 @ 600k → AES-256-GCM).
     */
open func pinWrap(pin: String) -> WrappedBlob {
    return try!  FfiConverterTypeWrappedBlob.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_pin_wrap(self.uniffiClonePointer(),
        FfiConverterString.lower(pin),$0
    )
})
}
    
    /**
     * Re-wrap the owned MK for a different credential/device. The Vault already holds
     * the MK, so this is a fresh wrap under `new_prf` (multi-device add).
     */
open func rewrap(newPrf: Data) -> WrappedBlob {
    return try!  FfiConverterTypeWrappedBlob.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_rewrap(self.uniffiClonePointer(),
        FfiConverterData.lower(newPrf),$0
    )
})
}
    
    /**
     * Seal arbitrary bytes (e.g. an embedding vector) at rest: `[0x02][IV][ct]`,
     * AAD = noteId. Fresh random IV per call.
     */
open func sealBytes(bytes: Data, aad: String) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_seal_bytes(self.uniffiClonePointer(),
        FfiConverterData.lower(bytes),
        FfiConverterString.lower(aad),$0
    )
})
}
    
    /**
     * Wrap the owned MK with a PRF-derived key → a storable prf-v1 blob. Salt (32B)
     * and IV (12B) are generated in-core with the CSPRNG — no nonce-reuse footgun.
     */
open func wrapWithPrf(prf: Data) -> WrappedBlob {
    return try!  FfiConverterTypeWrappedBlob.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_wrap_with_prf(self.uniffiClonePointer(),
        FfiConverterData.lower(prf),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVault: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Vault

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Vault {
        return Vault(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Vault) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Vault {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Vault, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lift(_ pointer: UnsafeMutableRawPointer) throws -> Vault {
    return try FfiConverterTypeVault.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lower(_ value: Vault) -> UnsafeMutableRawPointer {
    return FfiConverterTypeVault.lower(value)
}


/**
 * The result of a flush across the FFI: how many outbox ids were pushed vs. left queued.
 */
public struct FlushSummary {
    public var pushed: UInt32
    public var stillQueued: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pushed: UInt32, stillQueued: UInt32) {
        self.pushed = pushed
        self.stillQueued = stillQueued
    }
}



extension FlushSummary: Equatable, Hashable {
    public static func ==(lhs: FlushSummary, rhs: FlushSummary) -> Bool {
        if lhs.pushed != rhs.pushed {
            return false
        }
        if lhs.stillQueued != rhs.stillQueued {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pushed)
        hasher.combine(stillQueued)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFlushSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FlushSummary {
        return
            try FlushSummary(
                pushed: FfiConverterUInt32.read(from: &buf), 
                stillQueued: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FlushSummary, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.pushed, into: &buf)
        FfiConverterUInt32.write(value.stillQueued, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlushSummary_lift(_ buf: RustBuffer) throws -> FlushSummary {
    return try FfiConverterTypeFlushSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlushSummary_lower(_ value: FlushSummary) -> RustBuffer {
    return FfiConverterTypeFlushSummary.lower(value)
}


/**
 * The result of a pull across the FFI: rows seen, rows merged (last-write-wins winners +
 * applied tombstones), incoming deletes skipped as "don't-resurrect" (a delete for a row this
 * device never had), and the local edits dropped as stale by the outbox rebase (SUR-736/738 —
 * hosts read `superseded.len()` for the count).
 */
public struct PullSummary {
    public var pulled: UInt32
    public var merged: UInt32
    public var skippedTombstones: UInt32
    public var superseded: [SupersededEdit]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pulled: UInt32, merged: UInt32, skippedTombstones: UInt32, superseded: [SupersededEdit]) {
        self.pulled = pulled
        self.merged = merged
        self.skippedTombstones = skippedTombstones
        self.superseded = superseded
    }
}



extension PullSummary: Equatable, Hashable {
    public static func ==(lhs: PullSummary, rhs: PullSummary) -> Bool {
        if lhs.pulled != rhs.pulled {
            return false
        }
        if lhs.merged != rhs.merged {
            return false
        }
        if lhs.skippedTombstones != rhs.skippedTombstones {
            return false
        }
        if lhs.superseded != rhs.superseded {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pulled)
        hasher.combine(merged)
        hasher.combine(skippedTombstones)
        hasher.combine(superseded)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePullSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PullSummary {
        return
            try PullSummary(
                pulled: FfiConverterUInt32.read(from: &buf), 
                merged: FfiConverterUInt32.read(from: &buf), 
                skippedTombstones: FfiConverterUInt32.read(from: &buf), 
                superseded: FfiConverterSequenceTypeSupersededEdit.read(from: &buf)
        )
    }

    public static func write(_ value: PullSummary, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.pulled, into: &buf)
        FfiConverterUInt32.write(value.merged, into: &buf)
        FfiConverterUInt32.write(value.skippedTombstones, into: &buf)
        FfiConverterSequenceTypeSupersededEdit.write(value.superseded, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePullSummary_lift(_ buf: RustBuffer) throws -> PullSummary {
    return try FfiConverterTypePullSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePullSummary_lower(_ value: PullSummary) -> RustBuffer {
    return FfiConverterTypePullSummary.lower(value)
}


/**
 * One local edit the pull dropped because a strictly-newer remote row won last-write-wins
 * (SUR-736/738) — so a host can tell the user their offline edit was superseded. Not an
 * *unresolved* conflict: the remote already won under LWW. `discarded_updated_at` is the newest
 * dropped outbox stamp; `winning_updated_at` is the remote stamp that beat it. Ids + timestamps
 * only — never payload contents (E2EE: nothing decrypted or logged here).
 */
public struct SupersededEdit {
    public var table: String
    public var recordId: String
    public var discardedUpdatedAt: Int64
    public var winningUpdatedAt: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(table: String, recordId: String, discardedUpdatedAt: Int64, winningUpdatedAt: Int64) {
        self.table = table
        self.recordId = recordId
        self.discardedUpdatedAt = discardedUpdatedAt
        self.winningUpdatedAt = winningUpdatedAt
    }
}



extension SupersededEdit: Equatable, Hashable {
    public static func ==(lhs: SupersededEdit, rhs: SupersededEdit) -> Bool {
        if lhs.table != rhs.table {
            return false
        }
        if lhs.recordId != rhs.recordId {
            return false
        }
        if lhs.discardedUpdatedAt != rhs.discardedUpdatedAt {
            return false
        }
        if lhs.winningUpdatedAt != rhs.winningUpdatedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(table)
        hasher.combine(recordId)
        hasher.combine(discardedUpdatedAt)
        hasher.combine(winningUpdatedAt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSupersededEdit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SupersededEdit {
        return
            try SupersededEdit(
                table: FfiConverterString.read(from: &buf), 
                recordId: FfiConverterString.read(from: &buf), 
                discardedUpdatedAt: FfiConverterInt64.read(from: &buf), 
                winningUpdatedAt: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: SupersededEdit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.table, into: &buf)
        FfiConverterString.write(value.recordId, into: &buf)
        FfiConverterInt64.write(value.discardedUpdatedAt, into: &buf)
        FfiConverterInt64.write(value.winningUpdatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSupersededEdit_lift(_ buf: RustBuffer) throws -> SupersededEdit {
    return try FfiConverterTypeSupersededEdit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSupersededEdit_lower(_ value: SupersededEdit) -> RustBuffer {
    return FfiConverterTypeSupersededEdit.lower(value)
}


/**
 * The result of [`SyncEngine::sync`] — one pull then one flush, reported together.
 */
public struct SyncSummary {
    public var pull: PullSummary
    public var flush: FlushSummary

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pull: PullSummary, flush: FlushSummary) {
        self.pull = pull
        self.flush = flush
    }
}



extension SyncSummary: Equatable, Hashable {
    public static func ==(lhs: SyncSummary, rhs: SyncSummary) -> Bool {
        if lhs.pull != rhs.pull {
            return false
        }
        if lhs.flush != rhs.flush {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pull)
        hasher.combine(flush)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyncSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyncSummary {
        return
            try SyncSummary(
                pull: FfiConverterTypePullSummary.read(from: &buf), 
                flush: FfiConverterTypeFlushSummary.read(from: &buf)
        )
    }

    public static func write(_ value: SyncSummary, into buf: inout [UInt8]) {
        FfiConverterTypePullSummary.write(value.pull, into: &buf)
        FfiConverterTypeFlushSummary.write(value.flush, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncSummary_lift(_ buf: RustBuffer) throws -> SyncSummary {
    return try FfiConverterTypeSyncSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncSummary_lower(_ value: SyncSummary) -> RustBuffer {
    return FfiConverterTypeSyncSummary.lower(value)
}


/**
 * A stored `prf-v1` / PIN-transfer wrapped-key blob — base64 fields, exactly the
 * JS `{ wrappedKey, iv, salt }` shape. Standard base64, NOT url-safe (frozen).
 */
public struct WrappedBlob {
    public var wrappedKey: String
    public var iv: String
    public var salt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(wrappedKey: String, iv: String, salt: String) {
        self.wrappedKey = wrappedKey
        self.iv = iv
        self.salt = salt
    }
}



extension WrappedBlob: Equatable, Hashable {
    public static func ==(lhs: WrappedBlob, rhs: WrappedBlob) -> Bool {
        if lhs.wrappedKey != rhs.wrappedKey {
            return false
        }
        if lhs.iv != rhs.iv {
            return false
        }
        if lhs.salt != rhs.salt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(wrappedKey)
        hasher.combine(iv)
        hasher.combine(salt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWrappedBlob: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WrappedBlob {
        return
            try WrappedBlob(
                wrappedKey: FfiConverterString.read(from: &buf), 
                iv: FfiConverterString.read(from: &buf), 
                salt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WrappedBlob, into buf: inout [UInt8]) {
        FfiConverterString.write(value.wrappedKey, into: &buf)
        FfiConverterString.write(value.iv, into: &buf)
        FfiConverterString.write(value.salt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWrappedBlob_lift(_ buf: RustBuffer) throws -> WrappedBlob {
    return try FfiConverterTypeWrappedBlob.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWrappedBlob_lower(_ value: WrappedBlob) -> RustBuffer {
    return FfiConverterTypeWrappedBlob.lower(value)
}


/**
 * Errors that cross the FFI. Deliberately coarse: never leak key material or
 * distinguish auth-tag failure modes to callers.
 */
public enum CryptoError {

    
    
    case DecryptFailed
    case BadInput(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DecryptFailed
        case 2: return .BadInput(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .DecryptFailed:
            writeInt(&buf, Int32(1))
        
        
        case let .BadInput(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension CryptoError: Equatable, Hashable {}

extension CryptoError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


/**
 * Errors that cross the FFI from the sync engine. Coarse like [`crate::CryptoError`]: enough
 * for a host to distinguish "couldn't open the store" from "the flush hit the network", never
 * leaking key material or per-record server detail.
 */
public enum SyncError {

    
    
    case Store(String
    )
    case Flush(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyncError: FfiConverterRustBuffer {
    typealias SwiftType = SyncError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyncError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Store(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Flush(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SyncError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Store(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Flush(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension SyncError: Equatable, Hashable {}

extension SyncError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSupersededEdit: FfiConverterRustBuffer {
    typealias SwiftType = [SupersededEdit]

    public static func write(_ value: [SupersededEdit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSupersededEdit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SupersededEdit] {
        let len: Int32 = try readInt(&buf)
        var seq = [SupersededEdit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSupersededEdit.read(from: &buf))
        }
        return seq
    }
}
/**
 * Derive a `collection_memberships` primary key from its `(collection_id, note_id)` pair — the
 * FFI-exported mirror of surfc's `membershipId(collectionId, noteId)`, so a host can look up or
 * join local membership rows by the same deterministic id the sync layer writes (SUR-726). Thin
 * wrapper over [`crate::store::membership_id`]; collection id first.
 */
public func membershipId(collectionId: String, noteId: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_braird_core_fn_func_membership_id(
        FfiConverterString.lower(collectionId),
        FfiConverterString.lower(noteId),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_braird_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_braird_core_checksum_func_membership_id() != 9610) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_book() != 22816) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_collection() != 43786) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_collection_membership() != 42356) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_custom_idea() != 46286) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_lens() != 60504) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_note() != 25351) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_note_link() != 53465) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_enqueue_note_signals() != 33526) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_flush() != 39156) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_pull() != 8960) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_set_access_token() != 47386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_syncengine_sync() != 38790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_content_tag() != 23104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_decrypt_note() != 2957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_encrypt_note() != 22447) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_open_bytes() != 24917) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_pin_wrap() != 28802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_rewrap() != 61446) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_seal_bytes() != 63933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_wrap_with_prf() != 28929) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_constructor_syncengine_open() != 39686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_constructor_vault_generate() != 65080) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_constructor_vault_redeem_pin_transfer() != 25070) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_constructor_vault_unlock() != 13169) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all